/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2015-11-25 03:24:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("       <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>JSP Page</title>\r\n");
      out.write("        <link href=\"mystyle.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("<body>\r\n");
      out.write("        <!-- Defining the header section of the page -->\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div id=\"header1\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write(" \r\n");
      out.write("             </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"leftcol\">\r\n");
      out.write("<a href=\"login.jsp\">Login</a><br/><br/>\r\n");
      out.write("<a href=\"signup.jsp\">SignUp</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"rightcol\">");

   // Set refresh, autoload time as 1 seconds
   response.setIntHeader("Refresh", 59);
   // Get current time
   Calendar calendar = new GregorianCalendar();
   String am_pm;
   int hour = calendar.get(Calendar.HOUR);
   int minute = calendar.get(Calendar.MINUTE);
   int second = calendar.get(Calendar.SECOND);
   if(calendar.get(Calendar.AM_PM) == 0)
      am_pm = "AM";
   else
      am_pm = "PM";
   String CT = hour+":"+ minute +":"+ second +" "+ am_pm;
   out.println( CT );

      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("       <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("<!--LOGIN AND REGISTER CODE:-->\r\n");
      out.write("\r\n");
      out.write("<form action=\"login.jsp\" method=\"POST\">\r\n");
      out.write("                <section id=\"login\"><!-- login form -->\r\n");
      out.write("\r\n");
      out.write("                    <table align=\"right\" cellspacing=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"t\">\r\n");
      out.write("                                <label for=\"email\">Email</label>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"t\">\r\n");
      out.write("                                <label for=\"pass\">Password</label>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"text\" tabindex=\"1\" value=\"\" id=\"email\" name=\"email\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"password\" tabindex=\"2\" id=\"pass\" name=\"pass\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <label for=\"login_btn\" class=\"login_btn\">\r\n");
      out.write("                                    <input type=\"submit\" id=\"login_btn\" tabindex=\"4\" value=\"Log In\">\r\n");
      out.write("                                </label>                        \r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"b\">\r\n");
      out.write("                                <a rel=\"nofollow\" href=\"#\">Forgot your password?</a>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("\r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("            </form>\r\n");
      out.write("            <form action=\"reg.jsp\" method=\"post\">\r\n");
      out.write("                <table align=\"right\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td height=\"0\">\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td> \r\n");
      out.write("                            <img src=\"images/signup.png\"  />\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td height=\"20\">\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            Email:</td><td> <input type=\"text\" name=\"emailid\" value=\"\"   maxlength=125 /><br></td>\r\n");
      out.write("                        <td width=\"50\"></td>\r\n");
      out.write("                    </tr><br>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td height=\"10\">\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            Password:</td><td> <input type=\"password\" name=\"pass1\" value=\"\"   maxlength=10 /><br></td>\r\n");
      out.write("                    </tr><br>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td height=\"10\">\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            Confirm Password:</td><td> <input type=\"password\" name=\"pass2\" value=\"\"   maxlength=10 /><br></td>\r\n");
      out.write("                    </tr><br>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td height=\"10\">\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            First Name:</td><td> <input type=\"text\" name=\"fstname\" value=\"\" maxlength=\"10\" /><br></td>\r\n");
      out.write("                    </tr><br>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td height=\"10\">\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            Last Name:</td><td><input type=\"text\" name=\"lstname\" value=\"\" maxlength=\"10\" /><br></td>\r\n");
      out.write("                    </tr><br>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td height=\"10\">\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            Phone Number:</td><td><input type=\"text\" name=\"number\" value=\"\" maxlength=\"10\" /><br></td>\r\n");
      out.write("                    </tr><br>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td height=\"5\">\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                        </td><td><input type=\"submit\" name=\"register\" value=\"Register\"/></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("            <div class=\"wrap\">\r\n");
      out.write("                Footer Section\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
